# -*- coding: utf-8 -*-
"""Tu primera red neuronal en Python y Tensorflow
    https://www.youtube.com/watch?v=iX_on3VxZzk
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ehETBOVtCqe7G6HOvm84hfXba8Gd9ILW
"""

import tensorflow as tf
import numpy as np


# Recrea exactamente el mismo modelo solo desde el archivo
load_model = tf.keras.models.load_model('testModel.h5')

print("Hagamos una predicción!")
resultado2 = load_model.predict([100.0])
print("El resultado2 es " + str(resultado2) + " fahrenheit!")

